// =============================================================================
// File Name: soc_core_subsystem.v
// Design:    SoC CPU/cache subsystem integration
// =============================================================================

module soc_core_subsystem (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        cpu_int,
    input  wire        tlb_inv_en,
    input  wire [18:0] tlb_inv_vpn2,
    input  wire [7:0]  tlb_inv_asid,
    input  wire [1:0]  tlb_inv_scope,
    input  wire [5:0]  tlb_inv_wired_floor,

    output wire [3:0]  inst_awid,
    output wire [31:0] inst_awaddr,
    output wire [7:0]  inst_awlen,
    output wire [2:0]  inst_awsize,
    output wire [1:0]  inst_awburst,
    output wire [1:0]  inst_awlock,
    output wire [3:0]  inst_awcache,
    output wire [2:0]  inst_awprot,
    output wire        inst_awvalid,
    input  wire        inst_awready,
    output wire [31:0] inst_wdata,
    output wire [3:0]  inst_wstrb,
    output wire        inst_wlast,
    output wire        inst_wvalid,
    input  wire        inst_wready,
    input  wire [3:0]  inst_bid,
    input  wire [1:0]  inst_bresp,
    input  wire        inst_bvalid,
    output wire        inst_bready,
    output wire [3:0]  inst_arid,
    output wire [31:0] inst_araddr,
    output wire [7:0]  inst_arlen,
    output wire [2:0]  inst_arsize,
    output wire [1:0]  inst_arburst,
    output wire [1:0]  inst_arlock,
    output wire [3:0]  inst_arcache,
    output wire [2:0]  inst_arprot,
    output wire        inst_arvalid,
    input  wire        inst_arready,
    input  wire [3:0]  inst_rid,
    input  wire [31:0] inst_rdata,
    input  wire [1:0]  inst_rresp,
    input  wire        inst_rlast,
    input  wire        inst_rvalid,
    output wire        inst_rready,

    output wire [3:0]  data_awid,
    output wire [31:0] data_awaddr,
    output wire [7:0]  data_awlen,
    output wire [2:0]  data_awsize,
    output wire [1:0]  data_awburst,
    output wire [1:0]  data_awlock,
    output wire [3:0]  data_awcache,
    output wire [2:0]  data_awprot,
    output wire        data_awvalid,
    input  wire        data_awready,
    output wire [31:0] data_wdata,
    output wire [3:0]  data_wstrb,
    output wire        data_wlast,
    output wire        data_wvalid,
    input  wire        data_wready,
    input  wire [3:0]  data_bid,
    input  wire [1:0]  data_bresp,
    input  wire        data_bvalid,
    output wire        data_bready,
    output wire [3:0]  data_arid,
    output wire [31:0] data_araddr,
    output wire [7:0]  data_arlen,
    output wire [2:0]  data_arsize,
    output wire [1:0]  data_arburst,
    output wire [1:0]  data_arlock,
    output wire [3:0]  data_arcache,
    output wire [2:0]  data_arprot,
    output wire        data_arvalid,
    input  wire        data_arready,
    input  wire [3:0]  data_rid,
    input  wire [31:0] data_rdata,
    input  wire [1:0]  data_rresp,
    input  wire        data_rlast,
    input  wire        data_rvalid,
    output wire        data_rready,

    output wire        debug_stall,
    output wire        debug_flush
);

    mips_core u_core (
        .clk             (clk),
        .rst_n           (rst_n),
        .ext_int         ({5'd0, cpu_int}),
        .tlb_inv_en      (tlb_inv_en),
        .tlb_inv_vpn2    (tlb_inv_vpn2),
        .tlb_inv_asid    (tlb_inv_asid),
        .tlb_inv_scope   (tlb_inv_scope),
        .tlb_inv_wired_floor(tlb_inv_wired_floor),

        .inst_awid       (inst_awid),
        .inst_awaddr     (inst_awaddr),
        .inst_awlen      (inst_awlen),
        .inst_awsize     (inst_awsize),
        .inst_awburst    (inst_awburst),
        .inst_awlock     (inst_awlock),
        .inst_awcache    (inst_awcache),
        .inst_awprot     (inst_awprot),
        .inst_awvalid    (inst_awvalid),
        .inst_awready    (inst_awready),
        .inst_wdata      (inst_wdata),
        .inst_wstrb      (inst_wstrb),
        .inst_wlast      (inst_wlast),
        .inst_wvalid     (inst_wvalid),
        .inst_wready     (inst_wready),
        .inst_bid        (inst_bid),
        .inst_bresp      (inst_bresp),
        .inst_bvalid     (inst_bvalid),
        .inst_bready     (inst_bready),
        .inst_arid       (inst_arid),
        .inst_araddr     (inst_araddr),
        .inst_arlen      (inst_arlen),
        .inst_arsize     (inst_arsize),
        .inst_arburst    (inst_arburst),
        .inst_arlock     (inst_arlock),
        .inst_arcache    (inst_arcache),
        .inst_arprot     (inst_arprot),
        .inst_arvalid    (inst_arvalid),
        .inst_arready    (inst_arready),
        .inst_rid        (inst_rid),
        .inst_rdata      (inst_rdata),
        .inst_rresp      (inst_rresp),
        .inst_rlast      (inst_rlast),
        .inst_rvalid     (inst_rvalid),
        .inst_rready     (inst_rready),

        .data_awid       (data_awid),
        .data_awaddr     (data_awaddr),
        .data_awlen      (data_awlen),
        .data_awsize     (data_awsize),
        .data_awburst    (data_awburst),
        .data_awlock     (data_awlock),
        .data_awcache    (data_awcache),
        .data_awprot     (data_awprot),
        .data_awvalid    (data_awvalid),
        .data_awready    (data_awready),
        .data_wdata      (data_wdata),
        .data_wstrb      (data_wstrb),
        .data_wlast      (data_wlast),
        .data_wvalid     (data_wvalid),
        .data_wready     (data_wready),
        .data_bid        (data_bid),
        .data_bresp      (data_bresp),
        .data_bvalid     (data_bvalid),
        .data_bready     (data_bready),
        .data_arid       (data_arid),
        .data_araddr     (data_araddr),
        .data_arlen      (data_arlen),
        .data_arsize     (data_arsize),
        .data_arburst    (data_arburst),
        .data_arlock     (data_arlock),
        .data_arcache    (data_arcache),
        .data_arprot     (data_arprot),
        .data_arvalid    (data_arvalid),
        .data_arready    (data_arready),
        .data_rid        (data_rid),
        .data_rdata      (data_rdata),
        .data_rresp      (data_rresp),
        .data_rlast      (data_rlast),
        .data_rvalid     (data_rvalid),
        .data_rready     (data_rready),

        .debug_stall     (debug_stall),
        .debug_flush     (debug_flush)
    );

endmodule
