#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT_DIR=$(cd "${SCRIPT_DIR}/../.." && pwd)
CROSS_COMPILE=${CROSS_COMPILE:-mips64-linux-gnu-}
RUN_DIR=${RUN_DIR:-"${ROOT_DIR}/build/linux_boot/rtl_progress_gate"}
RUN_DIR=$(realpath -m "${RUN_DIR}")
HOST_TIMEOUT=${HOST_TIMEOUT:-180s}
RTL_CYCLE_LIMIT=${RTL_CYCLE_LIMIT:-1000000}
RTL_SIM_SEED=${RTL_SIM_SEED:-}
# Keep the default bounded because this runner invokes both the Linux build and
# VCS. Use JOBS=2+ only on a host with enough memory.
JOBS=${JOBS:-1}
KERNEL_PHYSICAL_START=${KERNEL_PHYSICAL_START:-0x88800000}
LINUX_PROFILE=${LINUX_PROFILE:-generic}
LINUX_VCS_EXTRA_ARGS=${LINUX_VCS_EXTRA_ARGS:-}
LINUX_DELAY_TRACE=${LINUX_DELAY_TRACE:-0}
LINUX_DELAY_TRACE_LIMIT=${LINUX_DELAY_TRACE_LIMIT:-256}
LINUX_DELAY_TRACE_START=${LINUX_DELAY_TRACE_START:-892434e0}
LINUX_DELAY_TRACE_END=${LINUX_DELAY_TRACE_END:-892434e4}
LINUX_DELAY_TRACE_CYCLE_START=${LINUX_DELAY_TRACE_CYCLE_START:-0}
LINUX_DELAY_TRACE_CYCLE_END=${LINUX_DELAY_TRACE_CYCLE_END:-0}
LINUX_GPR_TRACE=${LINUX_GPR_TRACE:-0}
LINUX_GPR_TRACE_LIMIT=${LINUX_GPR_TRACE_LIMIT:-256}
LINUX_GPR_TRACE_REG=${LINUX_GPR_TRACE_REG:-16}
LINUX_GPR_TRACE_CYCLE_START=${LINUX_GPR_TRACE_CYCLE_START:-0}
LINUX_GPR_TRACE_CYCLE_END=${LINUX_GPR_TRACE_CYCLE_END:-0}
LINUX_TARGET_DSIDE_TRACE=${LINUX_TARGET_DSIDE_TRACE:-0}
LINUX_TARGET_DSIDE_TRACE_LIMIT=${LINUX_TARGET_DSIDE_TRACE_LIMIT:-160}
LINUX_TARGET_TRACE_LINE=${LINUX_TARGET_TRACE_LINE:-40133b}
LINUX_TARGET_TRACE_CYCLE_START=${LINUX_TARGET_TRACE_CYCLE_START:-0}
LINUX_TARGET_TRACE_CYCLE_END=${LINUX_TARGET_TRACE_CYCLE_END:-0}
LINUX_UART_TRACE=${LINUX_UART_TRACE:-0}
LINUX_UART_TRACE_LIMIT=${LINUX_UART_TRACE_LIMIT:-256}
LINUX_APB_TRACE=${LINUX_APB_TRACE:-0}
LINUX_APB_TRACE_LIMIT=${LINUX_APB_TRACE_LIMIT:-512}
LINUX_APB_SELECT_TRACE=${LINUX_APB_SELECT_TRACE:-0}
LINUX_APB_SELECT_TRACE_LIMIT=${LINUX_APB_SELECT_TRACE_LIMIT:-512}
LINUX_VIC_TRACE=${LINUX_VIC_TRACE:-0}
LINUX_VIC_TRACE_LIMIT=${LINUX_VIC_TRACE_LIMIT:-256}
LINUX_EXCEPTION_TRACE=${LINUX_EXCEPTION_TRACE:-0}
LINUX_EXCEPTION_TRACE_LIMIT=${LINUX_EXCEPTION_TRACE_LIMIT:-256}
LINUX_EXCEPTION_TRACE_CYCLE_START=${LINUX_EXCEPTION_TRACE_CYCLE_START:-0}
LINUX_EXCEPTION_TRACE_CYCLE_END=${LINUX_EXCEPTION_TRACE_CYCLE_END:-0}
LINUX_WB_TRACE=${LINUX_WB_TRACE:-0}
LINUX_WB_TRACE_LIMIT=${LINUX_WB_TRACE_LIMIT:-256}
LINUX_WB_TRACE_CYCLE_START=${LINUX_WB_TRACE_CYCLE_START:-0}
LINUX_WB_TRACE_CYCLE_END=${LINUX_WB_TRACE_CYCLE_END:-0}
LINUX_MODE_TRACE=${LINUX_MODE_TRACE:-0}
LINUX_MODE_TRACE_LIMIT=${LINUX_MODE_TRACE_LIMIT:-64}
LINUX_MODE_TRACE_CYCLE_START=${LINUX_MODE_TRACE_CYCLE_START:-0}
LINUX_MODE_TRACE_CYCLE_END=${LINUX_MODE_TRACE_CYCLE_END:-0}
LINUX_PANIC_TRACE=${LINUX_PANIC_TRACE:-0}
LINUX_PANIC_TRACE_LIMIT=${LINUX_PANIC_TRACE_LIMIT:-32}
LINUX_PANIC_TRACE_START=${LINUX_PANIC_TRACE_START:-}
LINUX_PANIC_TRACE_END=${LINUX_PANIC_TRACE_END:-}
LINUX_CACHE_OWNER_TRACE=${LINUX_CACHE_OWNER_TRACE:-0}
LINUX_CACHE_OWNER_TRACE_LIMIT=${LINUX_CACHE_OWNER_TRACE_LIMIT:-256}
LINUX_RETIRE_TRACE=${LINUX_RETIRE_TRACE:-0}
LINUX_RETIRE_TRACE_MAX_RECORDS=${LINUX_RETIRE_TRACE_MAX_RECORDS:-1000000}
LINUX_REFILL_TRACE=${LINUX_REFILL_TRACE:-0}
LINUX_PROGRESS_TRACE=${LINUX_PROGRESS_TRACE:-1}
LINUX_STALL_TRACE=${LINUX_STALL_TRACE:-0}
LINUX_STALL_TRACE_LIMIT=${LINUX_STALL_TRACE_LIMIT:-256}
LINUX_STALL_TRACE_CYCLE_START=${LINUX_STALL_TRACE_CYCLE_START:-0}
LINUX_STALL_TRACE_PC=${LINUX_STALL_TRACE_PC:-0}
LINUX_REQUIRE_PROGRESS=${LINUX_REQUIRE_PROGRESS:-1}
LINUX_REQUIRE_USERSPACE=${LINUX_REQUIRE_USERSPACE:-0}
LINUX_EXCEPTION_TRACE=${LINUX_EXCEPTION_TRACE:-0}
LINUX_EXCEPTION_TRACE_LIMIT=${LINUX_EXCEPTION_TRACE_LIMIT:-256}
LINUX_EXCEPTION_FRAME_TRACE=${LINUX_EXCEPTION_FRAME_TRACE:-0}
LINUX_EXCEPTION_FRAME_TRACE_LIMIT=${LINUX_EXCEPTION_FRAME_TRACE_LIMIT:-64}
LINUX_EXCEPTION_FRAME_TRACE_CYCLE_START=${LINUX_EXCEPTION_FRAME_TRACE_CYCLE_START:-0}
LINUX_EXCEPTION_FRAME_TRACE_CYCLE_END=${LINUX_EXCEPTION_FRAME_TRACE_CYCLE_END:-0}
LINUX_EBASE_TRACE=${LINUX_EBASE_TRACE:-0}
LINUX_WB_TRACE=${LINUX_WB_TRACE:-0}
LINUX_EBASE_TRACE_LIMIT=${LINUX_EBASE_TRACE_LIMIT:-64}
LINUX_WB_TRACE_LIMIT=${LINUX_WB_TRACE_LIMIT:-256}
LINUX_MODE_TRACE=${LINUX_MODE_TRACE:-0}
LINUX_MODE_TRACE_LIMIT=${LINUX_MODE_TRACE_LIMIT:-64}
LINUX_PC_TRACE=${LINUX_PC_TRACE:-0}
LINUX_PC_TRACE_LIMIT=${LINUX_PC_TRACE_LIMIT:-256}
LINUX_PC_TRACE_RETIRE_ONLY=${LINUX_PC_TRACE_RETIRE_ONLY:-0}
LINUX_PC_TRACE_SYMBOL=${LINUX_PC_TRACE_SYMBOL:-kernel_init}
LINUX_PC_TRACE_START=${LINUX_PC_TRACE_START:-}
LINUX_PC_TRACE_END=${LINUX_PC_TRACE_END:-}
LINUX_PC_TRACE_CYCLE_START=${LINUX_PC_TRACE_CYCLE_START:-0}
LINUX_PC_TRACE_CYCLE_END=${LINUX_PC_TRACE_CYCLE_END:-0}
LINUX_WAIT_TRACE=${LINUX_WAIT_TRACE:-0}
LINUX_WAIT_TRACE_LIMIT=${LINUX_WAIT_TRACE_LIMIT:-256}
LINUX_TLB_TRACE=${LINUX_TLB_TRACE:-0}
LINUX_TLB_TRACE_LIMIT=${LINUX_TLB_TRACE_LIMIT:-256}
LINUX_TLB_TRACE_CYCLE_START=${LINUX_TLB_TRACE_CYCLE_START:-0}
LINUX_TLB_TRACE_CYCLE_END=${LINUX_TLB_TRACE_CYCLE_END:-0}
LINUX_FAULT_TRACE=${LINUX_FAULT_TRACE:-0}
LINUX_FAULT_TRACE_LIMIT=${LINUX_FAULT_TRACE_LIMIT:-256}
LINUX_FAULT_TRACE_START=${LINUX_FAULT_TRACE_START:-c0000000}
LINUX_FAULT_TRACE_END=${LINUX_FAULT_TRACE_END:-c0010000}
LINUX_FAULT_TRACE_CYCLE_START=${LINUX_FAULT_TRACE_CYCLE_START:-0}
LINUX_FAULT_TRACE_CYCLE_END=${LINUX_FAULT_TRACE_CYCLE_END:-0}
LINUX_VECTOR_TRACE=${LINUX_VECTOR_TRACE:-0}
LINUX_VECTOR_TRACE_LIMIT=${LINUX_VECTOR_TRACE_LIMIT:-1000}
LINUX_CACHEOP_TRACE_LIMIT=${LINUX_CACHEOP_TRACE_LIMIT:-0}
LINUX_CACHEOP_TRACE_LINE=${LINUX_CACHEOP_TRACE_LINE:-}
LINUX_CP0_TRACE_LIMIT=${LINUX_CP0_TRACE_LIMIT:-0}
LINUX_VECTOR_LINE_TRACE=${LINUX_VECTOR_LINE_TRACE:-0}
LINUX_VECTOR_LINE_TRACE_LIMIT=${LINUX_VECTOR_LINE_TRACE_LIMIT:-256}
LINUX_VECTOR_LINE=${LINUX_VECTOR_LINE:-470410}
SKIP_LINUX_BUILD=${SKIP_LINUX_BUILD:-0}
KERNEL_INPUT=${KERNEL:-}

# Progress is the evidence source for the post-reset progress criterion.  Do
# not spend a long simulator run only to reject it after completion when the
# caller explicitly disabled that trace.
if [[ "${LINUX_REQUIRE_PROGRESS}" == "1" &&
      "${LINUX_PROGRESS_TRACE}" != "1" ]]; then
    echo "RTL Linux progress gate: LINUX_REQUIRE_PROGRESS=1 requires LINUX_PROGRESS_TRACE=1" >&2
    exit 2
fi

# VCS warns and may truncate a %h plusarg when the payload includes 0x.
# Normalize trace addresses before forwarding them to the Verilog testbench.
strip_hex_prefix() {
    local value=${1:-}
    value=${value#0x}
    value=${value#0X}
    printf '%s' "${value}"
}

mkdir -p "${RUN_DIR}"

# Build a self-contained relocated image.  Keeping the kernel, DTB, Boot ROM,
# DDR image and simulator in one run directory makes this probe reproducible
# and avoids accidentally reusing an image from a different address layout.
if [[ "${SKIP_LINUX_BUILD}" == "1" || -n "${KERNEL_INPUT}" ]]; then
    if [[ "${SKIP_LINUX_BUILD}" == "1" && -z "${KERNEL_INPUT}" ]]; then
        echo "SKIP_LINUX_BUILD=1 requires KERNEL=/path/to/vmlinux" >&2
        exit 1
    fi
    if [[ -z "${KERNEL_INPUT}" ]]; then
        echo "RTL Linux progress gate: no KERNEL supplied for build skip" >&2
        exit 1
    fi
    test -s "${KERNEL_INPUT}"
    KERNEL_PATH=$(realpath "${KERNEL_INPUT}")
    printf 'Linux kernel build: SKIPPED (reusing supplied KERNEL)\nKERNEL=%s\n' "${KERNEL_PATH}" >"${RUN_DIR}/build.log"
else
    BUILD_DIR="${RUN_DIR}" JOBS="${JOBS}" KERNEL_PHYSICAL_START="${KERNEL_PHYSICAL_START}" \
        LINUX_PROFILE="${LINUX_PROFILE}" \
        "${SCRIPT_DIR}/build_linux_boot.sh" >"${RUN_DIR}/build.log" 2>&1
    KERNEL_PATH="${RUN_DIR}/kernel/vmlinux"
fi

# The kernel symbol layout changes with relocation and configuration. Resolve
# the bounded panic diagnostic window from the actual ELF instead of keeping a
# stale hard-coded address from an older image.
if [[ -z "${LINUX_PANIC_TRACE_START}" ]] && command -v "${CROSS_COMPILE}nm" >/dev/null 2>&1; then
    panic_symbol=$(${CROSS_COMPILE}nm -n "${KERNEL_PATH}" 2>/dev/null |
        awk '$3 == "panic" && !found { print $1; found = 1 }')
    if [[ "${panic_symbol}" =~ [0-9a-fA-F]{8}$ ]]; then
        panic_low=${panic_symbol: -8}
        LINUX_PANIC_TRACE_START="0x${panic_low}"
        panic_start_value=$((16#${panic_low}))
        LINUX_PANIC_TRACE_END=$(printf '0x%08x' $((panic_start_value + 0x400)))
    fi
fi
LINUX_PANIC_TRACE_START=${LINUX_PANIC_TRACE_START:-0x89245cbc}
LINUX_PANIC_TRACE_END=${LINUX_PANIC_TRACE_END:-0x89246010}
# Resolve a bounded function window from the supplied ELF when the caller
# enables PC tracing without explicit addresses.
if [[ "${LINUX_PC_TRACE}" == "1" && -z "${LINUX_PC_TRACE_START}" &&
      -z "${LINUX_PC_TRACE_END}" ]] && command -v "${CROSS_COMPILE}nm" >/dev/null 2>&1; then
    pc_symbol=$(${CROSS_COMPILE}nm -n "${KERNEL_PATH}" 2>/dev/null |
        awk -v symbol="${LINUX_PC_TRACE_SYMBOL}" '$3 == symbol && !found { print $1; found = 1 }')
    if [[ "${pc_symbol}" =~ [0-9a-fA-F]{8}$ ]]; then
        pc_low=${pc_symbol: -8}
        LINUX_PC_TRACE_START="0x${pc_low}"
        pc_start_value=$((16#${pc_low}))
        LINUX_PC_TRACE_END=$(printf '0x%08x' $((pc_start_value + 0x400)))
    fi
fi
LINUX_PC_TRACE_START=${LINUX_PC_TRACE_START:-0x00000000}
LINUX_PC_TRACE_END=${LINUX_PC_TRACE_END:-0x00000000}
LINUX_PC_TRACE_START=$(strip_hex_prefix "${LINUX_PC_TRACE_START}")
LINUX_PC_TRACE_END=$(strip_hex_prefix "${LINUX_PC_TRACE_END}")
LINUX_PANIC_TRACE_START=$(strip_hex_prefix "${LINUX_PANIC_TRACE_START}")
LINUX_PANIC_TRACE_END=$(strip_hex_prefix "${LINUX_PANIC_TRACE_END}")
LINUX_STALL_TRACE_PC=$(strip_hex_prefix "${LINUX_STALL_TRACE_PC}")
LINUX_CACHEOP_TRACE_LINE=$(strip_hex_prefix "${LINUX_CACHEOP_TRACE_LINE}")
LINUX_TARGET_TRACE_LINE=$(strip_hex_prefix "${LINUX_TARGET_TRACE_LINE}")
LINUX_DELAY_TRACE_START=$(strip_hex_prefix "${LINUX_DELAY_TRACE_START}")
LINUX_DELAY_TRACE_END=$(strip_hex_prefix "${LINUX_DELAY_TRACE_END}")
LINUX_FAULT_TRACE_START=$(strip_hex_prefix "${LINUX_FAULT_TRACE_START}")
LINUX_FAULT_TRACE_END=$(strip_hex_prefix "${LINUX_FAULT_TRACE_END}")
LINUX_VECTOR_LINE=$(strip_hex_prefix "${LINUX_VECTOR_LINE}")
KERNEL="${KERNEL_PATH}" \
    DTC="$(dirname "${KERNEL_PATH}")/scripts/dtc/dtc" \
    RUN_DIR="${RUN_DIR}/image" \
    "${SCRIPT_DIR}/build_rtl_linux_image.sh" >"${RUN_DIR}/image.log" 2>&1

if [[ ! -s "${RUN_DIR}/image/bootrom.hex" ||
      ! -s "${RUN_DIR}/image/ddr.hex" ]]; then
    echo "RTL Linux progress gate: image generation did not produce bootrom/ddr hex" >&2
    exit 1
fi

sim_dir="${RUN_DIR}/sim"
mkdir -p "${sim_dir}"
linux_retire_define=""
linux_retire_env=()
if [[ "${LINUX_RETIRE_TRACE}" == "1" ]]; then
    linux_retire_define=" +define+TB_RETIRE_TRACE"
    linux_retire_env=(RETIRE_TRACE="${sim_dir}/rtl_retire.jsonl")
fi
linux_l1_observation_define=""
if [[ " ${LINUX_VCS_EXTRA_ARGS} " == *" +define+SOC_CPU_NONBLOCKING_ENABLE=1 "* &&
      " ${LINUX_VCS_EXTRA_ARGS} " == *" +define+SOC_L1_NONBLOCKING_ENABLE=1 "* ]]; then
    linux_l1_observation_define=" +define+TB_L1_NONBLOCKING"
fi
linux_seed_arg=""
if [[ -n "${RTL_SIM_SEED}" ]]; then
    linux_seed_arg=" +ntb_random_seed=${RTL_SIM_SEED}"
fi
export LINUX_TRACE_WINDOW_ARGS="+LINUX_EXCEPTION_TRACE_CYCLE_START=${LINUX_EXCEPTION_TRACE_CYCLE_START} +LINUX_EXCEPTION_TRACE_CYCLE_END=${LINUX_EXCEPTION_TRACE_CYCLE_END} +LINUX_WB_TRACE_CYCLE_START=${LINUX_WB_TRACE_CYCLE_START} +LINUX_WB_TRACE_CYCLE_END=${LINUX_WB_TRACE_CYCLE_END} +LINUX_MODE_TRACE=${LINUX_MODE_TRACE} +LINUX_MODE_TRACE_LIMIT=${LINUX_MODE_TRACE_LIMIT} +LINUX_MODE_TRACE_CYCLE_START=${LINUX_MODE_TRACE_CYCLE_START} +LINUX_MODE_TRACE_CYCLE_END=${LINUX_MODE_TRACE_CYCLE_END}"
set +e
timeout "${HOST_TIMEOUT}" env \
    RUN_DIR="${sim_dir}" \
    FW_HEX="${RUN_DIR}/image/bootrom.hex" \
    SKIP_COVERAGE="${SKIP_COVERAGE:-0}" \
    VCS_EXTRA_ARGS="+define+SOC_LINUX_BOOT_ENABLE=1 +define+SOC_LINUX_GUEST_ENABLE=1 +define+SOC_PRODUCT_BOOT_ENABLE=1 +define+SOC_MMU_ENABLE=1 +define+TB_LINUX_BOOT +define+TB_LINUX_BOOT_TRACE${linux_retire_define}${linux_l1_observation_define} ${LINUX_VCS_EXTRA_ARGS}" \
    "${linux_retire_env[@]}" \
    SIM_EXTRA_ARGS="+BOOT_ROM_HEX=${RUN_DIR}/image/bootrom.hex +DDR_HEX=${RUN_DIR}/image/ddr.hex +LINUX_TRACE_LIMIT=${RTL_CYCLE_LIMIT} +LINUX_REFILL_TRACE=${LINUX_REFILL_TRACE} +LINUX_PROGRESS_TRACE=${LINUX_PROGRESS_TRACE} +LINUX_EXCEPTION_TRACE=${LINUX_EXCEPTION_TRACE} +LINUX_EBASE_TRACE=${LINUX_EBASE_TRACE} +LINUX_EBASE_TRACE_LIMIT=${LINUX_EBASE_TRACE_LIMIT} +LINUX_WB_TRACE=${LINUX_WB_TRACE} +LINUX_WB_TRACE_LIMIT=${LINUX_WB_TRACE_LIMIT} +LINUX_WAIT_TRACE=${LINUX_WAIT_TRACE} +LINUX_WAIT_TRACE_LIMIT=${LINUX_WAIT_TRACE_LIMIT} +LINUX_TLB_TRACE=${LINUX_TLB_TRACE} +LINUX_TLB_TRACE_LIMIT=${LINUX_TLB_TRACE_LIMIT} +LINUX_TLB_TRACE_CYCLE_START=${LINUX_TLB_TRACE_CYCLE_START} +LINUX_TLB_TRACE_CYCLE_END=${LINUX_TLB_TRACE_CYCLE_END} +LINUX_VECTOR_TRACE=${LINUX_VECTOR_TRACE} +LINUX_VECTOR_TRACE_LIMIT=${LINUX_VECTOR_TRACE_LIMIT} +LINUX_CACHEOP_TRACE_LIMIT=${LINUX_CACHEOP_TRACE_LIMIT} +LINUX_CACHEOP_TRACE_LINE=${LINUX_CACHEOP_TRACE_LINE} +LINUX_CP0_TRACE_LIMIT=${LINUX_CP0_TRACE_LIMIT} +LINUX_VECTOR_LINE_TRACE=${LINUX_VECTOR_LINE_TRACE} +LINUX_VECTOR_LINE_TRACE_LIMIT=${LINUX_VECTOR_LINE_TRACE_LIMIT} +LINUX_VECTOR_LINE=${LINUX_VECTOR_LINE} +LINUX_DELAY_TRACE=${LINUX_DELAY_TRACE} +LINUX_DELAY_TRACE_LIMIT=${LINUX_DELAY_TRACE_LIMIT} +LINUX_DELAY_TRACE_START=${LINUX_DELAY_TRACE_START} +LINUX_DELAY_TRACE_END=${LINUX_DELAY_TRACE_END} +LINUX_DELAY_TRACE_CYCLE_START=${LINUX_DELAY_TRACE_CYCLE_START} +LINUX_DELAY_TRACE_CYCLE_END=${LINUX_DELAY_TRACE_CYCLE_END} +LINUX_TARGET_DSIDE_TRACE=${LINUX_TARGET_DSIDE_TRACE} +LINUX_TARGET_DSIDE_TRACE_LIMIT=${LINUX_TARGET_DSIDE_TRACE_LIMIT} +LINUX_TARGET_TRACE_LINE=${LINUX_TARGET_TRACE_LINE} +LINUX_TARGET_TRACE_CYCLE_START=${LINUX_TARGET_TRACE_CYCLE_START} +LINUX_TARGET_TRACE_CYCLE_END=${LINUX_TARGET_TRACE_CYCLE_END} +LINUX_UART_TRACE=${LINUX_UART_TRACE} +LINUX_UART_TRACE_LIMIT=${LINUX_UART_TRACE_LIMIT} +LINUX_VIC_TRACE=${LINUX_VIC_TRACE} +LINUX_VIC_TRACE_LIMIT=${LINUX_VIC_TRACE_LIMIT} +LINUX_PANIC_TRACE=${LINUX_PANIC_TRACE} +LINUX_PANIC_TRACE_LIMIT=${LINUX_PANIC_TRACE_LIMIT} +LINUX_PANIC_TRACE_START=${LINUX_PANIC_TRACE_START} +LINUX_PANIC_TRACE_END=${LINUX_PANIC_TRACE_END}" \
    LINUX_EXTRA_SIM_ARGS="+LINUX_GPR_TRACE=${LINUX_GPR_TRACE} +LINUX_GPR_TRACE_LIMIT=${LINUX_GPR_TRACE_LIMIT} +LINUX_GPR_TRACE_REG=${LINUX_GPR_TRACE_REG} +LINUX_GPR_TRACE_CYCLE_START=${LINUX_GPR_TRACE_CYCLE_START} +LINUX_GPR_TRACE_CYCLE_END=${LINUX_GPR_TRACE_CYCLE_END} +LINUX_CACHE_OWNER_TRACE=${LINUX_CACHE_OWNER_TRACE} +LINUX_CACHE_OWNER_TRACE_LIMIT=${LINUX_CACHE_OWNER_TRACE_LIMIT} +LINUX_EXCEPTION_TRACE_LIMIT=${LINUX_EXCEPTION_TRACE_LIMIT} +LINUX_EXCEPTION_FRAME_TRACE=${LINUX_EXCEPTION_FRAME_TRACE} +LINUX_EXCEPTION_FRAME_TRACE_LIMIT=${LINUX_EXCEPTION_FRAME_TRACE_LIMIT} +LINUX_EXCEPTION_FRAME_TRACE_CYCLE_START=${LINUX_EXCEPTION_FRAME_TRACE_CYCLE_START} +LINUX_EXCEPTION_FRAME_TRACE_CYCLE_END=${LINUX_EXCEPTION_FRAME_TRACE_CYCLE_END} +LINUX_FAULT_TRACE=${LINUX_FAULT_TRACE} +LINUX_FAULT_TRACE_LIMIT=${LINUX_FAULT_TRACE_LIMIT} +LINUX_FAULT_TRACE_START=${LINUX_FAULT_TRACE_START} +LINUX_FAULT_TRACE_END=${LINUX_FAULT_TRACE_END} +LINUX_FAULT_TRACE_CYCLE_START=${LINUX_FAULT_TRACE_CYCLE_START} +LINUX_FAULT_TRACE_CYCLE_END=${LINUX_FAULT_TRACE_CYCLE_END} +LINUX_EBASE_TRACE=${LINUX_EBASE_TRACE} +LINUX_EBASE_TRACE_LIMIT=${LINUX_EBASE_TRACE_LIMIT} +LINUX_WB_TRACE=${LINUX_WB_TRACE} +LINUX_WB_TRACE_LIMIT=${LINUX_WB_TRACE_LIMIT} +LINUX_VECTOR_TRACE=${LINUX_VECTOR_TRACE} +LINUX_PANIC_TRACE_START=${LINUX_PANIC_TRACE_START} +LINUX_MODE_TRACE=${LINUX_MODE_TRACE} +LINUX_MODE_TRACE_LIMIT=${LINUX_MODE_TRACE_LIMIT} +LINUX_PC_TRACE=${LINUX_PC_TRACE} +LINUX_PC_TRACE_LIMIT=${LINUX_PC_TRACE_LIMIT} +LINUX_PC_TRACE_RETIRE_ONLY=${LINUX_PC_TRACE_RETIRE_ONLY} +LINUX_PC_TRACE_SYMBOL=${LINUX_PC_TRACE_SYMBOL} +LINUX_PC_TRACE_START=${LINUX_PC_TRACE_START} +LINUX_PC_TRACE_END=${LINUX_PC_TRACE_END} +RETIRE_TRACE_MAX_RECORDS=${LINUX_RETIRE_TRACE_MAX_RECORDS} +LINUX_PC_TRACE_CYCLE_START=${LINUX_PC_TRACE_CYCLE_START} +LINUX_PC_TRACE_CYCLE_END=${LINUX_PC_TRACE_CYCLE_END} +LINUX_STALL_TRACE=${LINUX_STALL_TRACE} +LINUX_STALL_TRACE_LIMIT=${LINUX_STALL_TRACE_LIMIT} +LINUX_STALL_TRACE_CYCLE_START=${LINUX_STALL_TRACE_CYCLE_START} +LINUX_STALL_TRACE_PC=${LINUX_STALL_TRACE_PC}${linux_seed_arg}" \
    LINUX_APB_SIM_ARGS="+LINUX_APB_TRACE=${LINUX_APB_TRACE} +LINUX_APB_TRACE_LIMIT=${LINUX_APB_TRACE_LIMIT} +LINUX_APB_SELECT_TRACE=${LINUX_APB_SELECT_TRACE} +LINUX_APB_SELECT_TRACE_LIMIT=${LINUX_APB_SELECT_TRACE_LIMIT}" \
    "${ROOT_DIR}/tb/soc_test/run.sh" >"${RUN_DIR}/sim.log" 2>&1
status=$?
set -e

if [[ "${status}" -ne 0 ]]; then
    echo "RTL Linux progress gate: simulator command failed or timed out (status ${status})" >&2
    exit "${status}"
fi

test -s "${sim_dir}/sim.log" || {
    echo "RTL Linux progress gate: simulator log is missing" >&2
    exit 1
}

# A bounded probe is useful only when it demonstrates post-boot instruction
# progress.  It is deliberately not a boot gate: userspace and its success
# marker are checked by the future RTL Linux boot gate.
if [[ "${LINUX_REQUIRE_PROGRESS}" == "1" ]] &&
   ! rg -q 'LINUX_PROGRESS_TRACE cycle=[1-9][0-9]* pc=(?!bfc00000)' \
        --pcre2 "${sim_dir}/sim.log"; then
    echo "RTL Linux progress gate: no post-reset CPU progress observed (status ${status})" >&2
    exit 1
fi
if rg -q 'REGRESSION_TEST_FAILED|Comprehensive SoC Test Failed|tb_mips_soc: ERROR' \
        "${sim_dir}/sim.log"; then
    echo "RTL Linux progress gate: simulator reported a regression failure" >&2
    exit 1
fi

marker_count=$(rg -c 'MIPS32_SOC_LINUX_BOOT_SUCCESS' "${sim_dir}/sim.log" || echo 0)
result="PASS (bounded post-reset progress probe)"
if [[ "${LINUX_REQUIRE_USERSPACE}" == "1" && "${marker_count}" -eq 0 ]]; then
    result="FAIL (Linux userspace marker not observed)"
fi
cat >"${RUN_DIR}/completion_report.md" <<EOF
# RTL Linux Progress Gate

- Result: ${result}
- Host timeout: ${HOST_TIMEOUT}
- RTL cycle limit: ${RTL_CYCLE_LIMIT}
- RTL simulation seed: ${RTL_SIM_SEED:-default}
- Linux profile: ${LINUX_PROFILE}
- Delay trace: ${LINUX_DELAY_TRACE} (limit=${LINUX_DELAY_TRACE_LIMIT}, window=${LINUX_DELAY_TRACE_START}..${LINUX_DELAY_TRACE_END})
- UART trace: ${LINUX_UART_TRACE} (limit=${LINUX_UART_TRACE_LIMIT})
- APB trace: ${LINUX_APB_TRACE} (limit=${LINUX_APB_TRACE_LIMIT})
- APB select trace: ${LINUX_APB_SELECT_TRACE} (limit=${LINUX_APB_SELECT_TRACE_LIMIT})
- VIC trace: ${LINUX_VIC_TRACE} (limit=${LINUX_VIC_TRACE_LIMIT})
- Panic trace: ${LINUX_PANIC_TRACE} (limit=${LINUX_PANIC_TRACE_LIMIT})
- Panic trace window: ${LINUX_PANIC_TRACE_START}..${LINUX_PANIC_TRACE_END}
- Fault/address trace: ${LINUX_FAULT_TRACE} (limit=${LINUX_FAULT_TRACE_LIMIT}, window=${LINUX_FAULT_TRACE_START}..${LINUX_FAULT_TRACE_END}, cycles=${LINUX_FAULT_TRACE_CYCLE_START}..${LINUX_FAULT_TRACE_CYCLE_END})
- Exception-frame trace: ${LINUX_EXCEPTION_FRAME_TRACE} (limit=${LINUX_EXCEPTION_FRAME_TRACE_LIMIT}, cycles=${LINUX_EXCEPTION_FRAME_TRACE_CYCLE_START}..${LINUX_EXCEPTION_FRAME_TRACE_CYCLE_END})
- GPR trace: ${LINUX_GPR_TRACE} (reg=${LINUX_GPR_TRACE_REG}, limit=${LINUX_GPR_TRACE_LIMIT}, cycles=${LINUX_GPR_TRACE_CYCLE_START}..${LINUX_GPR_TRACE_CYCLE_END})
- Cache owner trace: ${LINUX_CACHE_OWNER_TRACE} (limit=${LINUX_CACHE_OWNER_TRACE_LIMIT}, line=${LINUX_TARGET_TRACE_LINE})
- Retire trace: ${LINUX_RETIRE_TRACE} (limit=${LINUX_RETIRE_TRACE_MAX_RECORDS})
- Refill/progress/exception/EBase trace: ${LINUX_REFILL_TRACE}/${LINUX_PROGRESS_TRACE}/${LINUX_EXCEPTION_TRACE}/${LINUX_EBASE_TRACE}
- Stall-reason trace: ${LINUX_STALL_TRACE} (limit=${LINUX_STALL_TRACE_LIMIT}, cycle-start=${LINUX_STALL_TRACE_CYCLE_START}, pc=${LINUX_STALL_TRACE_PC})
- Require progress heartbeat: ${LINUX_REQUIRE_PROGRESS}
- Require userspace marker: ${LINUX_REQUIRE_USERSPACE}
- WB trace: ${LINUX_WB_TRACE}
- Exception trace cycles: ${LINUX_EXCEPTION_TRACE_CYCLE_START}..${LINUX_EXCEPTION_TRACE_CYCLE_END}
- WB trace cycles: ${LINUX_WB_TRACE_CYCLE_START}..${LINUX_WB_TRACE_CYCLE_END}
- EBase trace limit: ${LINUX_EBASE_TRACE_LIMIT}
- WB trace limit: ${LINUX_WB_TRACE_LIMIT}
- Mode trace: ${LINUX_MODE_TRACE} (limit=${LINUX_MODE_TRACE_LIMIT}, cycles=${LINUX_MODE_TRACE_CYCLE_START}..${LINUX_MODE_TRACE_CYCLE_END})
- PC trace: ${LINUX_PC_TRACE} (retire-only=${LINUX_PC_TRACE_RETIRE_ONLY}, limit=${LINUX_PC_TRACE_LIMIT}, window=${LINUX_PC_TRACE_START}..${LINUX_PC_TRACE_END}, cycles=${LINUX_PC_TRACE_CYCLE_START}..${LINUX_PC_TRACE_CYCLE_END})
- PC trace symbol: ${LINUX_PC_TRACE_SYMBOL}
- WAIT trace: ${LINUX_WAIT_TRACE} (limit=${LINUX_WAIT_TRACE_LIMIT})
- Image manifest: ${RUN_DIR}/image/image_manifest.txt
- Simulator log: ${sim_dir}/sim.log
- Linux userspace success markers observed: ${marker_count}
- Scope: relocated Linux image construction, Boot ROM/DDR preload, RTL
  compilation/elaboration and bounded post-reset CPU progress.
- Boundary: this is not RTL/QEMU Linux differential signoff. The userspace
  marker is informational by default and becomes a required boot criterion
  when LINUX_REQUIRE_USERSPACE=1.
EOF

if [[ "${LINUX_REQUIRE_USERSPACE}" == "1" && "${marker_count}" -eq 0 ]]; then
    echo "RTL Linux progress gate: userspace marker not observed" >&2
    exit 1
fi
echo "RTL Linux progress gate: PASS (userspace marker count=${marker_count}, simulator status=${status})"
