// =============================================================================
// File Name: apb_boot_status.v
// Design:    Always-on APB boot status and reset-cause block
// Description:
//   Retains the boot stage and failure code across the one-cycle watchdog
//   reset generated by apb_wdt. A raw rst_n (POR/external reset) clears the
//   block. Software owns the stage and failure-code writes; reset causes are
//   sticky and write-one-to-clear.
//
// Register map (APB, byte offsets):
//   0x00 BOOT_STAGE  RW  stage[7:0], reset 0x00
//   0x04 FAILURE     RW  failure code; non-zero writes set, zero clears
//   0x08 RESET_CAUSE RW sticky bits: [0] POR, [1] watchdog; write-one-clear
// =============================================================================

module apb_boot_status (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        wdt_reset,

    input  wire        psel,
    input  wire        penable,
    input  wire        pwrite,
    input  wire [4:0]  paddr,
    input  wire [31:0] pwdata,
    output reg  [31:0] prdata,
    output wire        pready,
    output wire        pslverr
);

    reg [7:0]  stage_r;
    reg [31:0] failure_r;
    reg [1:0]  reset_cause_r;

    wire wr = psel & penable & pwrite;
    wire rd = psel & penable & ~pwrite;

    assign pready  = 1'b1;
    assign pslverr = 1'b0;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            stage_r       <= 8'h00;
            failure_r     <= 32'h0000_0000;
            reset_cause_r <= 2'b01;
        end else begin
            // The watchdog pulse is generated in the same always-on domain
            // and remains observable after the reset it caused is released.
            if (wdt_reset)
                reset_cause_r[1] <= 1'b1;

            if (wr) begin
                case (paddr[4:2])
                    3'b000: stage_r <= pwdata[7:0];
                    3'b001: failure_r <= pwdata;
                    3'b010: reset_cause_r <= reset_cause_r & ~pwdata[1:0];
                    default: begin end
                endcase
            end
        end
    end

    always @(*) begin
        prdata = 32'h0000_0000;
        if (rd) begin
            case (paddr[4:2])
                3'b000: prdata = {24'h0, stage_r};
                3'b001: prdata = failure_r;
                3'b010: prdata = {30'h0, reset_cause_r};
                default: prdata = 32'h0000_0000;
            endcase
        end
    end
endmodule
