TEST_NAME       := mmu_process_pressure
TEST_SOURCES    := product_process_pressure.s
FW_TOP_DIR      := ../..
CUSTOM_BOOT     := 1
LINKER_SCRIPT   := $(CURDIR)/link.ld
include $(FW_TOP_DIR)/common/Makefile.rules
