TEST_NAME    := mmu_refill
TEST_SOURCES := main.c boot_mmu.s ../../common/print.c ../../common/excpt.c
FW_TOP_DIR   := ../..
CUSTOM_BOOT  := 1
LINKER_SCRIPT := $(CURDIR)/link.ld
include $(FW_TOP_DIR)/common/Makefile.rules
