# End-to-end product CacheErr recovery firmware.
TEST_NAME       := product_cacheerr
TEST_SOURCES    := product_cacheerr.s
FW_TOP_DIR      := ../..
CUSTOM_BOOT     := 1
LINKER_SCRIPT   := $(CURDIR)/link.ld
include $(FW_TOP_DIR)/common/Makefile.rules
